- migrations/sql/V2017.10.17.1416__RemoveTouchstoneDDset.sql
Issue i815 - 
touchstone->touchstone_demographic_dataset was erroneously added in i662.
Removing it should have no consequences;
touchstone_demographic_dataset->touchstone is what we want, and we have it.
> Drop unwanted touchstone column

- migrations/sql/V2017.11.21.1729__AddBurdenOutcomes.sql
These burden outcomes were added manually to production, hence the `ON CONFLICT` clause.
> new migration

- migrations/sql/V2018.01.24.17.02__AddEstimateWriterRole.sql
- scripts/test-migrate.sh
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1385
I realised while working on this that we no longer had a way of testing migrations location: the `teamcity-migrate.sh` script now uses the common `start.sh` script, which is shared across multiple repos. This script insists on running a migrate image from our registry: it can't be a locally build one.
To solve this, I wrote a new `test-migrate.sh` script which duplicates some code from `start.sh`. I think this is preferable to making `start.sh` more configurable, as it's already at a level of complexity that almost warrants a python program. It's fine if `test-migrate.sh` falls behind a bit, and occasionally fails and needs updating when you run it: It's only used by developers during development, and TeamCity still exists as the …
> i1385:  Add role for stochastic ingest tool 

- migrations/sql/V2018.01.26.1000__AddGaviCountryStatus.sql
This adds two new tables - the data are expected to change over time so they're linked against touchstone (in the import PR for montagu-data the data that comes in will be identical but it's not large - about 10K rows per touchstone). The enum entries are from GAVI themselves so they do not conform to our text keys.  I could add a third column to the enum table with that, with some minor tweaks to the data import
> Create tables to hold new gavi metadata

- annex/provision.sh
This is the same as in montagu-ci:provision/setup-docker.sh
It was not actually run as-is because the machine was already provisioned,
but this is the same approach as used elsewhere.  In the meantime I've
run it manually.
> i1113 Move docker directory to data disk

- migrations/sql/V2018.02.20.1505__AddUserGroup.sql
3 new tables. `user_group` and `user_group_user`  are slightly confusing - can you think of better names!?
This migration also creates a user group for each user, unix style, creates other standard groups, and inserts all members of a modelling group into the user group 'modellers'.
> Add user group tables

- backup/Dockerfile
This results in a really cryptic non-error error:
```
Collecting docopt
Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Building wheels for collected packages: docopt
Running setup.py bdist_wheel for docopt ... error
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-elw77ng_/docopt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpynbbc1sdpip-wheel- --python-tag cp35:
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help
error: invalid command 'bdist_wheel' …
```
> i1676: Fix pip installation

- migrations/sql-annex/V2018.04.23.1339__BurdenEstimateStochastic_RemoveArtificialKey.sql
- migrations/sql/V2018.04.23.1101__BurdenEstimate_RemoveArtificialKey.sql
- migrations/sql/V2018.04.23.1101__ChangeBurdenEstimateIdToBigSerial.sql
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1431
Changed this migration to drop the artificial primary key and add a natural one.
I can't see anyway of directly converting the existing unique constraint to a primary key, sadly, so this will take a while.
> i1431 Drop burden_estimate.id

- backup/Dockerfile
- backup/README.md
- backup/barman-montagu
- backup/bin/setup-barman
- backup/bin/update-nightly
- backup/demo_montagu.sh
- backup/install
- backup/requirements.txt
- backup/testing/montagu-deploy.json
This does a few different things together to make this work:
- the cron job is moved from the host machine to within the long-running container.  This simplifies deployment (and removal) but is a controversial decision (e.g. https://medium.com/@jonbaldie/how-to-run-cron-jobs-inside-docker-containers-26964315b582).  But now that we need two cron jobs I think this is better - and barman is weird enough anyway.
- the container gets another volume `/nightly` which will be the volume that can be used to get a recent backup for staging machines via bb8/starport
- there is a script `update-nightly` that tries to move into place the new backup as smoothly as possible.  The backup is done into a directory on the `/nightly` volume, then the previous restore is removed, then the new one is moved …
> I1710 - nightly backups in barman

- backup/README.md
- backup/barman-montagu
- backup/bin/setup-barman
- backup/etc/barman.d.in/montagu.json
- bin/enable-replication.sh
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1771
This adds options to barman to allow the user to:
* Choose a different registry to use (e.g. our public vimc one)
* A new required option for which replication slot to use
First merge #80.
> i1771: New barman options

- migrations/sql/V2018.07.16.1330__BurdenEstimateExpectations.sql
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1949
Hi all. These tables are intended to define what burden estimates we are wanting for each modelling group. They hang off responsibility, to give us maximal flexibility.
They allow us to define how many rows we want (via year, age, cohort, and country) and how many columns we want (outcomes).
These will then be used to generate templates and validate uploads.
> i1949: Add burden estimate expectations tables

- bin/montagu-wait.sh
It frequently takes just over 15 seconds on my two work stations to get the database up - particularly the first time I run it after logging on. It might be nice to try and reduce the db startup time, but in the meantime this tiny PR will make my work less frustrating.
> Increase default wait duration

- .gitignore
- scripts/update-docs
I *think* this is enough to make it work, but it's hard to test for reasons
* we only want to generate docs when `montagu-db` is on master
* we want to do this on TC
TC is set up with ssh keys to allow pushing to montagu-db-docs and I've added a build step.  I toyed with a separate build configuration but because we don't have a snapshot dependency, TC was telling me that was a bad idea
> i2325: Script to update docs

- migrations/sql/V2018.12.13.1313__AddModellerRole.sql
Modellers need to be able to call `GET /modelling-groups/` from the API to access the contribution portal. (Maybe we could re-write the portal to avoid this but we need an immediate fix.)
The existing role `member` is scoped to a group id, whereas the `GET /modelling-groups/` endpoint is locked down to only users with global group reading permission. So we need a new global role, `modeller`, which we can assign group reading permission to and then give to all members of a modelling group. 
Actually I think this makes sense anyway, since there are some global permissions we do want modellers to have (as opposed to just all users to have) and so far we have had no mechanism for this.
> make members of a group also have a global 'modeller' role

- migrations/sql/V2019.05.03.0830__CreateDettlImportLog.sql
For `dettl` imports to be able to run an import log table must exist.
This will PR will
* Create the import log table as expected by https://github.com/vimc/dettl/blob/21ea478534edbef729da6b08c1ccf52e656a55b1/inst/sql/postgresql/create_log_table.sql
Note: We should wait for that PR to be merged into master before merging this to ensure there will be no changes to the structure of the expected table.
> vimc-2901 Create dettl import log table

- annex/README.md
- annex/deploy.sh
- annex/destroy.sh
This PR fixes some bitrot here:
* correct documentation
* safer destroy
* somewhat nicer deployment
I've confirmed that this is running the high-memory configuration and you can too if you deploy this locally (with `./deploy.sh`)
```
docker exec -it montagu_db_annex psql -U vimc -d montagu -c "SELECT name, setting, unit, min_val, max_val FROM pg_settings WHERE name = 'work_mem';"
```
There is still bits that could be removed:
* `restore_test` and `testing` seem probably so outdated that it is of only archaelogical interest?
* The README section on "Preparing" is probably removable.
> VIMC-3430: updates to annex deploy script and docs

- migrations/sql/V2020.02.19.1135__RemoveReportPermissions.sql
These are now meaningless as orderly db handles its own roles and permissions.
> VIMC-3447 delete report related perms

- scripts/start.sh
- scripts/stop.sh
The start script is used in local development and testing. For the API build, it's useful to be able to specify the network that the container starts on, so that other dependencies can be run on the same network.
To test that this works, the following should all work; in the first 2 cases note from the output that the db container is running on `db_nw` and in the last case that it is running on network `test_nw`:
* `./scripts/start.sh master`
* `./scripts/start.sh master 5432`
* `./scripts/start.sh master 5432 test_nw`
> vimc-4225 make network configurable in start script

- migrations/sql/V2020.11.09.1222__AddCoverageSetMetadata.sql
adds table for storing metadata about coverage sets when uploaded via the portal
> vimc-4363 add coverage_set_metadata table

- migrations/sql/V2020.11.09.1222__AddCoverageSetMetadata.sql
Realised I got this wrong - each upload contains multiple coverage sets, so this should be a 1-many mapping.
> vimc-4363 allow for 1-many mapping of metadata to coverage set

- migrations/sql/V2020.11.10.1545__AddSubnationalFlagToCoverage.sql
Made it nullable because we don't want to wrongly infer this for existing data.
> vimc-4361 add subnational flag to coverage table

- migrations/sql/V2021.07.05.1731__ResponsibilitySetComment.sql
Create table for comments to be attached to responsibility sets, analogous to the recently-added [`responsibility_comment`](https://github.com/vimc/montagu-db/blob/master/migrations/sql/V2021.05.21.1323__ResponsibilityComment.sql). If the latter didn't exist then there could be an argument for a generic `comment` table, with `responsibility_comment` and `responsibility_set_comment` just acting as intermediaries, but this would complicate navigation through the database. Strong opinions either way welcome.
> VIMC-4767 Add comments to responsibility sets

- migrations/sql/V2021.11.17.1525__CoverageSouceFrom.sql
context: we are trying to add additional checks so that almost-duplicates coming from different information sources do not conflict with one another
changes: add a column to record the source of information for each vaccination activity
> add `source_from` column to coverage table

- migrations/sql/V2022.03.23.1702__AddGavi74.sql
- migrations/sql/V2022.03.23.1702__AssGavi74.sql
Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6273
Hi @kgaythorpe and @r-ash, here is a migration script adding column `gavi74` to table `country_metadata`.
> vimc-6273: add gavi74 column to country_metadata
