minimal/common/permission.csv
minimal/common/role.csv
minimal/common/role_permission.csv

https://vimc.myjetbrains.com/youtrack/issue/VIMC-407

Create new 'reports.read' and 'reports.review' permissions

---

minimal/common/role.csv
minimal/common/role_permission.csv

https://vimc.myjetbrains.com/youtrack/issue/VIMC-485

Add reports-reader role.

---

functions/indexes.sql
schema/montagu-db.sql
schema/montagu-db.xml

https://vimc.myjetbrains.com/youtrack/issue/VIMC-463

Provide table for API access log

---

migrations/sql/V2017.09.18.1058__TrackCurrentModelAndVersion.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-686

Rework model version bits

---

bin/restore-dump.sh

As seen on a failed restore on science.

Stop restore on first error

---

bin/restore-dump.sh

Fixes bug that I introduced in #19 ([VIMC-797](https://vimc.myjetbrains.com/youtrack/issue/VIMC-797)) - deploy with restore is broken currently.

i804 Use correct argument name for stopping on error

---

migrations/README.md

Just a minor tweak to the readme

i587 - Update vault password location

---

migrations/sql/V2017.11.17.1112__AddBurdenEstimateSetType.sql
scripts/teamcity-migrate.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-928

Add burden estimate set type

---

migrations/sql/V2017.11.20.1226__CorrectBurdenEstimateSetTypeCodes.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1054

Fix type codes

---

import/Dockerfile
import/build.sh

Our old db import container was created with the legacy data import on teamcity and we need a new one.

i1049 - new import image

---

scripts/start.sh

I am now using this as a replacement for our existing script in the API. This makes it behave in the same way as that script, and generally seems like a useful feature.

Always pull fresh versions if possible

---

scripts/start.sh

Part of https://vimc.myjetbrains.com/youtrack/issue/VIMC-949

Add option to expose annex too

---

migrations/sql-annex/V2017.12.07.1405__AddModelRunToBurdenEstimateStochastic.sql
migrations/sql/V2017.12.07.1256__AddModelRunToBurdenEstimate.sql

Either one of you to review.
https://vimc.myjetbrains.com/youtrack/issue/VIMC-1148

i1148: Add `model_run` to `burden_estimate` and `burden_estimate_stochastic`. 

---

migrations/sql/V2017.12.11.1446__AddCurrentStochasticBurdenEstimateSetToResponsibility.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-930

Add current stochastic burden estimate set

---

migrations/sql/V2017.12.20.1500__AddIsOpenToResponsibility.sql

This is a stopgap until we get the responsibility set split by disease

i1234 - Add new "is_open" column to responsibility

---

import/Dockerfile

i1437 Add tidyr to import image

---

migrations/sql-annex/V2018.02.02__AddModelRunToBurdenEstimateStochasticUniqueConstraint.sql
scripts/test-migrate.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1442

i1442: Add model_run to unique constraint

---

migrations/sql/V2018.02.22.1535__MigrateRoles.sql

This migration should be deployed in conjunction with this API change:
https://github.com/vimc/montagu-api/pull/247

add identity groups and migrate roles

---

migrations/sql/V2018.02.27.1344__AddScopeReportReadingRole.sql

This just adds the scoped role to the database. We will assign it for specific reports in a data import script.

i1548 - add new scoped report reading role

---

migrations/sql/V2018.03.02.1328__RemoveUserRoleTable.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1555

i1555: Remove user_role

---

migrations/sql/V2018.03.22.1601__AddBurdenOutcomes.sql

new migration

---

migrations/sql/V2018.04.09.1043__MakeIsOpenDefaultForResponsibilities.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1650

Add default to is_open

---

migrations/sql/V2018.04.23.1101__BurdenEstimate_RemoveArtificialKey.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1431

Also update foreign table mapping

---

migrations/sql-annex/V2018.04.23.1339__BurdenEstimateStochastic_RemoveArtificialKey.sql
migrations/sql/V2018.04.23.1101__BurdenEstimate_RemoveArtificialKey.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1431

Don't have a primary key on burden_estimate

---

backup/Dockerfile
backup/README.md
backup/barman-montagu
backup/bin/recover-last
backup/bin/recover-last-no-server
backup/bin/wipe-recover
backup/demo.sh

Primarily restore -> recover (were both used, inconsistently)
Also documents where the files are located on the annex

i1711: Documentation fixes from deploy

---

bin/enable-replication.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1771

i1771: Add an extra replication slot on deploy

---

bin/montagu-wait.sh

* customisable length of time it will wait for
* stops when container does not come up(!)
* prints error message if container doesn't come up

i1884: montagu-wait.sh improvements

---

annex/restore-test/provision/setup-vault.sh
annex/restore-test/provision/test-restore.sh
annex/restore-test/test-annex-restore.sh
annex/vault-auth

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1681
http://teamcity.montagu.dide.ic.ac.uk:8111/project.html?projectId=montagu&tab=projectOverview&branch_montagu=i1681

i1681: Replace calls to `vault auth` with `vault login` 

---

migrations/sql/V2018.07.18.1411__AllowResponsibilitiesToShareExpectation.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1966

i1966: Allow expectations to be used by more than one responsibility

---

migrations/sql/V2018.08.15.1317__MakeMoreExpectationColumnsRequired.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2057

i2057: Add migration to make description and version NOT NULL

---

backup/aws/bin/run-barman.sh
backup/aws/bin/startup.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2175

i2175: Use autossh

---

conf/README.md
conf/postgresql.conf
conf/postgresql.production.conf.in

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2218

i2218: Increase max wal senders to 7

---

annex/README.md
annex/deploy.sh
annex/destroy.sh

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2219
There were a number of things out of date / not quite right, so I fixed them too. Please review carefully.

i2219: Use production db config for annex

---

conf/postgresql.conf

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2219
To be merged after https://github.com/vimc/montagu/pull/118 and https://github.com/vimc/montagu-db/pull/103

i2219 remove duplicated settings

---

backup/aws/aws-barman
backup/aws/barman_ssh_client.py
backup/aws/bin/run-barman.sh
backup/aws/bin/run-machine-metrics.sh
backup/aws/bin/startup.sh
backup/aws/security_group.py

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2244
This is deployed on EC2. If you checkout this branch and run `./aws-barman status` it will tell you the URL of both metrics endpoints on the instance.

i2244: Add machine metrics to EC2 instance

---

migrations/sql/V2018.09.17.1344__MoreCountryMetadata.sql

Hi @richfitz, I have updated the sql in ways I think are right. I will come back to it, and double check it against the related import script. Thanks.

I2182: update country metadata migration script.

---

backup/aws/bin/startup.sh

I've run this manually on the machine but this would be good to have in place for the next reboot

i2274: Stop kubelet after disabling it

---

scripts/update-docs

Merge after https://github.com/vimc/montagu-db-docs/pull/5

i2325: Install dependencies before running script

---

migrations/sql/V2018.12.07.1121__AddGaviSupportLevels.sql

on conflict do nothing because these have already been manually added to some databases

new migration to add gavi support levels

---

migrations/sql/V2019.03.21.1151__RemoveModellerRole.sql

Deletes the now obsolete "modeller" role and any associated data

I2732 - remove global "modeller" role

---

migrations/sql/V2019.03.28.1347__ResponsibilitiesReadForAdminAndMembersOnly.sql

Wasn't sure if funder needed to be in there...?

Vimc 2810 Only give responsibilities.read permission to users who should have it

---

migrations/sql/V2019.06.26.1411__AddGaviSupportLevels.sql

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2970
may you review and make the migration?

VIMC-2970: add new gavi support levels

---

migrations/sql/V2020.01.01.1741__AddUniqueConstraintToDemographicStatType.sql

See https://github.com/vimc/montagu-api/pull/411

vimc-3209 add unique constraint to demographic stat type table

---

conf/postgresql.production.conf.in

Details about why we want to do this are in the ticket https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-3382

Update shared buffers on prod config to 12GB

---

migrations/sql/V2020.02.14.1123__EnableCrosstab.sql

needed for https://github.com/vimc/montagu-api/pull/421

migration to enable crosstab

---

annex/deploy.sh

As for #165 but for the annex, which is what is causing the problem for the report

VIMC-3509: Increase shared memory size for annex db too

---

migrations/sql/V2020.06.17.1735__ConstrainScenarioDescription.sql

Task:
Set scenario_description.scenario_type as non nullable.
Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-4072

add migration script

---

README.md
annex/README.md
annex/deploy.sh
annex/restore-test/provision/setup-vault.sh
docs/generate.py
import/build.sh
migrations/README.md
scripts/start.sh
scripts/teamcity-migrate.sh
scripts/teamcity-schema.sh

Associated PRs:
* https://github.com/vimc/montagu-api/pull/426
* https://github.com/vimc/montagu/pull/178

vimc-4229 remove all refs to the private registry

---

README.md
annex/README.md
buildkite/pipeline.yml
migrations/README.md
scripts/build-main-image.sh
scripts/build-migrations-image.sh
scripts/common
scripts/test.sh
scripts/update-docs

Minor changes to the existing scripts to pull out a `common` file and run tests in a separate step from builds. Also updated the README and added a build badge.

vimc-4231 add build to buildkite

---

migrations/sql/V2021.05.21.1323__ResponsibilityComment.sql
migrations/sql/V2021.06.15.0826__ResponsibilitiesReviewForAdmin.sql
scripts/run.sh

Summary:
* Add new table for comments
* Add `responsibilities.review` role for admin users
* Fix `run.sh`: relative paths in `migrations/Dockerfile` require top-level working directory

VIMC-4734 Add comments to responsibilities

---

migrations/sql/V2022.10.04.1554__AddActivityType.sql

Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6763/new-activitytype
This is to create a new activity type

vimc-6763: add new activity type

---

migrations/sql/V2022.10.17.1005__AddBurdenOutcome.sql

Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6781/montagu-db-migration-new-burden-outcome-yll

vimc-6781: add new burden outcome

---

bin/montagu-wait.sh
migrations/sql/V2023.10.16.1150__UpdateCountry.sql
scripts/start.sh

Task:
Update two country names.
Youtrack:
https://mrc-ide.myjetbrains.com/youtrack/issue/VIMC-6896/Change-country-names-in-VIMC-database

vimc-6896: update country name
